### ISSUE TITLE
Can u please provide the code for training

### ISSUE THREAD

**Issue by ravitejagullapudi** [agaldran/a_v_uncertain#2]
If not possible to share as public please share to me personally

**Comment by agaldran** [comment]
Man I feel very bad about this repo, I intended to clean and release the code a long time ago, but then I got lost into a milion other things. I think I have the entire project in my external hard-drive, with data and everything. If you want I can send it in a zipped folder, and you can try to make sense of it? I warn you, it is just a series of notebooks... I could help you if you don't understand anything on them of course

**Comment by ravitejagullapudi** [comment]
Yeah, please do it... I needed..

**Comment by agaldran** [comment]
Ok, so just give me an email I will transfer it to you right now

**Comment by agaldran** [comment]
or send me an email (agaldran at gmail)

**Comment by ravitejagullapudi** [comment]
Mail : ravitejagullapudi@gmail.com

**Comment by siddhantpreventamedical** [comment]
Mail: siddhantbhavsar@gmail.com.
Hello @agaldran would you please send that to me too. I really liked your work.

**Comment by TerenceLiu98** [comment]
@agaldran Sorry for bothering you, would you send me the code of training either? mail: `me@cklau.cc`

**Comment by agaldran** [comment]
No bother. This repository is quite old, and is not maintained, because a couple of years later I developed a better version of this work, in which I trained a minimal model for the same task, and others, and got much better results. 

So I recommend you to please forget about this code and use instead this repo: https://github.com/agaldran/lwnet 

The paper is here: https://www.nature.com/articles/s41598-022-09675-y
